name = "TermInput"
uuid = "e53b28ee-00f8-475a-85b8-1918fdda0ee8"
authors = ["Jameson Nash <vtjnash@gmail.com>"]
version = "0.1.0"

[deps]
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"

[weakdeps]
JuliaSyntaxHighlighting = "ac6e5ff7-fb65-4e79-a425-ec3bc9c03011"

[extensions]
TermInputHighlightExt = "JuliaSyntaxHighlighting"

[compat]
InteractiveUtils = "1.10"
JuliaSyntaxHighlighting = "1.12"
Markdown = "1.10"
REPL = "1.10"
StyledStrings = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
